version: '3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: /usr/src/app/start_flask.sh
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./app/.env
    networks:
      - smart-view
    ports:
      - 8000:8000
  db:
    image: mysql:5.7.35
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3307:3306
    env_file:
      - ./app/.env
    networks:
      - smart-view

networks:
  smart-view: